######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 16 20:51:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
	codeArea.h \
	codeEditor.h \
	syntaxHighlighter.h \
	lineNumberArea.h

HEADERS += \
	projectInfo.h

SOURCES += \
	codeArea.cpp \
	codeEditor.cpp \
	syntaxHighlighter.cpp \
	main.cpp \
	lineNumberArea.cpp
